 CREATE DATABASE IF NOT EXISTS MIRROR_DB;
 CREATE SCHEMA IF NOT EXISTS MIRROR;
  CREATE TABLE IF NOT EXISTS "MIRROR_DB"."MIRROR"."T_ML_CSSE_COVID_19_DAILY_REPORTS_SNOWFLAKE" (
    "FIPS" TEXT,
    "ADMIN2" TEXT,
    "PROVINCE_STATE" TEXT,
    "COUNTRY_REGION" TEXT,
    "LAST_UPDATE" TEXT,
    "LAT" TEXT,
    "LONG_" TEXT,
    "CONFIRMED" TEXT,
    "DEATHS" TEXT,
    "RECOVERED" TEXT,
    "ACTIVE" TEXT,
    "COMBINED_KEY" TEXT,
    "INCIDENT_RATE" TEXT,
    "CASE_FATALITY_RATIO" TEXT,
    "file_date" TIMESTAMP,
    filename TEXT,
    file_row_number TEXT,
    file_last_modified TIMESTAMP,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT
);