 CREATE DATABASE IF NOT EXISTS COMMON_DB;
 CREATE SCHEMA IF NOT EXISTS MIRROR;
  CREATE TABLE IF NOT EXISTS "COMMON_DB"."MIRROR"."T_ML_CSSE_COVID_19_DAILY_REPORTS_POSTGRES_TR" (
    "FIPS" TEXT,
    "ADMIN2" TEXT,
    "PROVINCE_STATE" TEXT,
    "COUNTRY_REGION" TEXT,
    "LAST_UPDATE" TEXT,
    "LAT" TEXT,
    "LONG_" TEXT,
    "CONFIRMED" TEXT,
    "DEATHS" TEXT,
    "RECOVERED" TEXT,
    "ACTIVE" TEXT,
    "COMBINED_KEY" TEXT,
    "INCIDENT_RATE" TEXT,
    "CASE_FATALITY_RATIO" TEXT,
    "FILE_DATE" TIMESTAMP,
    "FILE_NAME" TEXT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT
);