 CREATE DATABASE IF NOT EXISTS MIRROR_DB;
 CREATE SCHEMA IF NOT EXISTS MIRROR;
  CREATE TABLE IF NOT EXISTS MIRROR_DB.MIRROR.T_ML_CSSE_COVID_19_DAILY_REPORTS (
    FIPS STRING,
    ADMIN2 STRING,
    PROVINCE_STATE STRING,
    COUNTRY_REGION STRING,
    LAST_UPDATE STRING,
    LAT STRING,
    LONG_ STRING,
    CONFIRMED STRING,
    DEATHS STRING,
    RECOVERED STRING,
    ACTIVE STRING,
    COMBINED_KEY STRING,
    INCIDENT_RATE STRING,
    CASE_FATALITY_RATIO STRING,
    file_date TIMESTAMP,
    filename STRING,
    file_row_number STRING,
    file_last_modified TIMESTAMP,
    CREATED_DTS TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DTS TIMESTAMP,
    UPDATED_BY STRING,
    UNIQUE_HASH_ID STRING,
    ROW_HASH_ID STRING
);