 CREATE DATABASE IF NOT EXISTS STAGE_DB;
 CREATE SCHEMA IF NOT EXISTS STAGE;
  CREATE TABLE IF NOT EXISTS "STAGE_DB"."STAGE"."T_STG_CSSE_COVID_19_DAILY_REPORTS_SNOWFLAKE" (
    "FIPS" FLOAT,
    "ADMIN2" TEXT,
    "PROVINCE_STATE" TEXT,
    "COUNTRY_REGION" TEXT,
    "LAST_UPDATE" TEXT,
    "LAT" FLOAT,
    "LONG_" FLOAT,
    "CONFIRMED" NUMBER,
    "DEATHS" NUMBER,
    "RECOVERED" FLOAT,
    "ACTIVE" FLOAT,
    "COMBINED_KEY" TEXT,
    "INCIDENT_RATE" FLOAT,
    "CASE_FATALITY_RATIO" FLOAT,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);