 CREATE DATABASE IF NOT EXISTS STAGE_DB;
 CREATE SCHEMA IF NOT EXISTS STAGE;
 CREATE OR REPLACE TABLE STAGE_DB.STAGE.T_STG_NETFLIX_MOVIES_AND_TV_SHOWS (
    TITLE STRING,
    TYPE STRING,
    GENRE STRING,
    RELEASE_YEAR NUMBER,
    RATING STRING,
    DURATION STRING,
    COUNTRY STRING,
    CREATED_DTS TIMESTAMP,
    CREATED_BY STRING,
    UPDATED_DTS TIMESTAMP,
    UPDATED_BY STRING,
    ACTIVE_FL STRING,
    EFFECTIVE_START_DATE TIMESTAMP,
    EFFECTIVE_END_DATE TIMESTAMP,
    UNIQUE_HASH_ID STRING,
    ROW_HASH_ID STRING
);