 CREATE DATABASE IF NOT EXISTS COMMON_DB;
 CREATE SCHEMA IF NOT EXISTS STAGE;
  CREATE TABLE IF NOT EXISTS "COMMON_DB"."STAGE"."T_STG_CSSE_COVID_19_DAILY_REPORTS_POSTGRES" (
    "FIPS" DOUBLE PRECISION,
    "ADMIN2" TEXT,
    "PROVINCE_STATE" TEXT,
    "COUNTRY_REGION" TEXT,
    "LAST_UPDATE" TEXT,
    "LAT" DOUBLE PRECISION,
    "LONG_" DOUBLE PRECISION,
    "CONFIRMED" NUMERIC,
    "DEATHS" NUMERIC,
    "RECOVERED" DOUBLE PRECISION,
    "ACTIVE" DOUBLE PRECISION,
    "COMBINED_KEY" TEXT,
    "INCIDENT_RATE" DOUBLE PRECISION,
    "CASE_FATALITY_RATIO" DOUBLE PRECISION,
    "CREATED_DTS" TIMESTAMP,
    "CREATED_BY" TEXT,
    "UPDATED_DTS" TIMESTAMP,
    "UPDATED_BY" TEXT,
    "UNIQUE_HASH_ID" TEXT,
    "ROW_HASH_ID" TEXT,
    "ACTIVE_FL" TEXT,
    "EFFECTIVE_START_DATE" TIMESTAMP,
    "EFFECTIVE_END_DATE" TIMESTAMP
);